SELECT C.CNUM, C.CNAME, C.CITY
FROM CUST C
WHERE C.SNUM IN (
    SELECT O.SNUM
    FROM ORDERS O
    JOIN CUST C2 ON O.CNUM = C2.CNUM
    WHERE C2.SNUM = C.SNUM
    GROUP BY O.SNUM
    HAVING COUNT(DISTINCT C2.CNUM) > 1
);
