SELECT S.SNAME, C.CNAME
FROM SALESPEOPLE S
LEFT OUTER JOIN CUST C ON S.SNUM = C.SNUM

UNION

SELECT S.SNAME, 'No Customer' AS CNAME
FROM SALESPEOPLE S
WHERE S.SNUM NOT IN (SELECT DISTINCT SNUM FROM CUST);
