SELECT S.SNAME, C.CNAME, C.CNUM
FROM SALESPEOPLE S
JOIN CUST C ON S.SNUM = C.SNUM
JOIN ORDERS O ON C.CNUM = O.CNUM
GROUP BY S.SNAME, C.CNAME, C.CNUM
HAVING COUNT(O.ONUM) > 1
ORDER BY S.SNAME, C.CNAME;
