/*----->Using ALL*/

SELECT C.CNUM, C.CNAME, C.RATING
FROM CUST C
WHERE C.RATING > ALL (
    SELECT C2.RATING
    FROM CUST C2
    WHERE C2.CITY = 'Paris'
);


/*----->Using NOT EXISTS*/


SELECT C.CNUM, C.CNAME, C.RATING
FROM CUST C
WHERE NOT EXISTS (
    SELECT 1
    FROM CUST C2
    WHERE C2.CITY = 'Paris'
    AND C2.RATING >= C.RATING
);
