/*--->Using ANY*/


SELECT S.SNUM, S.SNAME
FROM SALESPEOPLE S
WHERE NOT EXISTS (
    SELECT 1
    FROM CUST C
    WHERE C.SNUM = C.SNUM
    AND C.CITY = S.CITY
);


/*--->Using ALL*/

SELECT S.SNUM, S.SNAME
FROM SALESPEOPLE S
WHERE NOT EXISTS (
    SELECT 1
    FROM CUST C
    WHERE C.SNUM = S.SNUM
    AND C.CITY != S.CITY
);
